version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile 경로
    image: laravel_app:latest
    platform: linux/amd64
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./php-config/php.ini:/usr/local/etc/php/php.ini # Custom PHP configuration
    networks:
      - laravel

  web:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      retries: 3
      timeout: 5s

networks:
  laravel:
    driver: bridge

volumes:
  mysql_data:
    driver: local
