worker_processes auto;

events {
    worker_connections 1024;  # 최대 동시 연결 수
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name dbv2020.onoffmix.test;  # 서버 이름 설정

        root /var/www/html/public;  # Laravel public 디렉토리 경로
        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass app:9000;  # PHP-FPM 컨테이너 이름과 포트
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
